### ISSUE TITLE
Imperative API Documentation

### ISSUE THREAD

**Issue by tuliofaria** [pqina/flip#1]
Hi, first of all, congratulations for the great library.
It's the best flip card I've found! It works really amazing.

I'm wondering how can I use it imperatively? So if I have a div where I want to render the flip, how I can add it to this div having only the div reference?

My idea is to integrate in a side project I'm building in ReactJS.
If you have any idea.

**Comment by rikschennink** [comment]
Hi! Thanks :D 

There's a small entry on this here: https://pqina.nl/tick/#view-javascript

```js
// create Tick Counter
var tick = Tick.DOM.create({
    value: 1234,
    view:
    // definition for top level tick element
    {
        children:[
            // presenter object
            {
                root: 'div',
                layout: 'horizontal fill',
                children: [
                    // presenter object
                    {
                        view: 'flip'
                    },
                    // presenter object
                    {
                        view: 'line',
                        root: 'div'
                    }
                ]
            }
        ]
    }
});

// add Tick Counter to body element
document.body.appendChild(tick.root);
```

I haven't experimented with this, but I guess you could also build declarative views with React.

**Comment by tuliofaria** [comment]
Hi, thanks for your guidance.
I was able to create a component in React to represent the flip display. And it works nice when changing the value from outside component:

```
import React, { useRef, useEffect } from "react";
/*global Tick */
const Flipr = ({ children, value }) => {
  const divRef = useRef();
  const tickRef = useRef();
  useEffect(() => {
    const currDiv = divRef.current;
    const handleInit = tick => {
      tickRef.current = tick;
    };
    Tick.DOM.create(currDiv, {
      value: value,
      didInit: handleInit,
      repeat: true,
      view:
        // definition for top level tick element
        {
          children: [
            // presenter object
            {
              root: "div",
              //style: ".tick",
              layout: "horizontal middle",
              repeat: true,
              transform: "upper -> split -> delay(random, 100, 150)",
              children: [
                // presenter object
                {
                  view: "flip",
                  transform: "ascii -> arrive -> round -> char(a-zA-Z@!)"
                }
              ]
            }
          ]
        }
    });
  });
  useEffect(() => {
    if (tickRef.current) {
      tickRef.current.value = value;
    }
  }, [value]);
  return <div ref={divRef} />;
};
export default Flipr;

```

**Comment by Raghav-Kumar-Jha** [comment]
import React, { useState, useEffect } from "react";
import Tick from "@pqina/flip";

function Parent() {
	return (
		<div>
			<TimedCountdown timeInMin={180}/>   {/* Total time in Minutes  */}
		</div>
	)
}

function TimedCountdown({timeInMin}){
    const [secLeft, setSec]= useState(0);
    const [minLeft, setMin] = useState(0);
    const [hourLeft, setHour] = useState(0);

 useEffect(()=>{
        // converting time in Minutes into Hours, Minutes and Seconds
        var hours = (timeInMin / 60);
        var rhours = Math.floor(hours);
        var minutes = (hours - rhours) * 60;
        var rminutes = Math.round(minutes);
        setMin(rminutes);
        setHour(rhours);
    },[])

return (
<div> Show Timed Countdown Here </div>
)
}

![Timer](https://user-images.githubusercontent.com/36503061/79117874-edc0c500-7da9-11ea-8559-28b43eb14d93.JPG)

**Comment by deadcoder0904** [comment]
Hey @tuliofaria your example isn't working for me? Anything I'm doing wrong?

Here's the codesandbox 🤜  https://codesandbox.io/s/react-flip-countdown-timer-8tin3?file=/src/Flipr.js

`Flipr.js` is your exact code & `Flip.js` is taken from this repo. Notice, `Flip.js` is working while the exact same thing `Flipr.js` isn't. The only difference is one is hooks & other is using classes.

And I didn't manage to get `Tick.count.down` working so if you or @Raghav-Kumar-Jha or @rikschennink has any suggestions, please let me know :)

**Comment by rikschennink** [comment]
@deadcoder0904 If I click the buttons the flipper is updated?

**Comment by deadcoder0904** [comment]
I have 2 flippers. Well not I was editing so I have 3 of them now. Your original React code is named as `Flip.js` then `Flipr.js` which is the above code with hooks & my 3rd one `Flippen.js`.

`Flip.js` works perfectly fine that's what you are seeing. I couldn't manage to get `Flipr.js` work. I tried it yesterday & today. So read up today again on React Hooks & created `Flippen.js` & made it work. Here's the code:

```js
import React, { useRef, useEffect } from "react";
import Tick from "@pqina/flip";
import "@pqina/flip/dist/flip.min.css";

export const Flippen = ({ value }) => {
  const divRef = useRef();
  const tickRef = useRef();

  useEffect(() => {
    const didInit = tick => {
      tickRef.current = tick;
    };

    const currDiv = divRef.current;
    const tickValue = tickRef.current;
    Tick.DOM.create(currDiv, {
      value,
      didInit
    });
    return () => Tick.DOM.destroy(tickValue);
  });

  useEffect(() => {
    if (tickRef.current) {
      tickRef.current.value = value;
    }
  }, [value]);

  return (
    <div ref={divRef} className="tick">
      <div data-repeat="true">
        <span data-view="flip">Tick</span>
      </div>
    </div>
  );
};
```

And here's the codesandbox - https://codesandbox.io/s/react-flip-countdown-timer-8tin3?file=/src/Flippen.js

Notice, there are 3 horizontal lines for 3 counters but only 2 are displayed. @tuliofaria's code isn't working for me. It's not a worry since I managed to get it work with hooks.

The only gripe right now is how to make it work with `Tick.count.down` which I'll be trying now. If you have any solutions, let me know. Also, if you can publish `tick` to NPM that'd be wonderful as I'm currently using it in a project & don't want to add links & scripts tag :)

**Comment by rikschennink** [comment]
@deadcoder0904 now on npm at https://www.npmjs.com/package/@pqina/tick
