### ISSUE TITLE
Help with some front-end functionalities 

### ISSUE THREAD

**Issue by amichel86** [pqina/flip#13]
Hello, I came across this plugin in a recent front-end newsletter and I decided to give it a try. First of all, thank you so much, the look is great and it does a lot of stuff! However I implemented it today and I need some assistance with some things. I took the "Event Countdown" example.

URL: http://theintegrateur.com/clients/css/visite-virtuelle.html

- On load, why does the countdown grow from small to original size? (It does that on every browser)
- How come on resize it's not responsive? (It works if I refresh the page though)
- Is there a way to put a "font-size" on .tick-label so that it doesn't go too far down from .tick-group > div

Thanks! :)

May I pay you a beer or coffee?

**Comment by rikschennink** [comment]
Thanks!

- Flip will try to fill all available horizontal space on each "tick". It probably has to do with the parent container changing size based on maybe the logo loading? Giving the parent container a width of 100% or a fixed width but based on the viewport size will probably fix the problem.
- Probably related to nr 1
- You can style each element see the example templates on the product page.

I don't have a donation page, this work is made possible by the [Doka Image Editor](https://pqina.nl/doka/) I build and sell, so should you ever need one, think of me ;-)

**Comment by amichel86** [comment]
@rikschennink hey!

If you go back on my link and ctrl + f5 (to clear cache), you'll see that I removed other elements in the same container, removed custom CSS and put a 100% width but the growing still occurs. When I inspect it, the div has a font size of 130px and a few seconds after, it gets changed to 136px.

The responsiveness works now, any idea what is missing?

**Comment by rikschennink** [comment]
@amichel86 I can check in a couple weeks, currently on a short vacation.

**Comment by rikschennink** [comment]
@amichel86 I'm terribly sorry that this got away from me. I've had to prioritise other things in life but should've at least let you know. Will close for now as it's probably no longer relevant.
