### ISSUE TITLE
Usage with React: Failed to execute 'removeChild' on 'Node'

### ISSUE THREAD

**Issue by stewartrule** [pqina/flip#15]
calling ` Tick.DOM.destroy(ref.current);`when cleaning up a React component can sometimes throw the following error:

`Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.`

The issue can be reproduced here by clicking the 'toggle' button: https://codesandbox.io/s/react-flip-demo-z715o?file=/src/App.js 

Maybe flip could expose a second cleanup method (that only removes listeners) that doesn't also try to modify the dom, so React (or Vue) can call it safely?

---

tick.core.module.js

```js
var destroyer = (function (state) {
  return {
    destroy: function destroy() {
 
      if (state.root && state.root.parentNode) {
        // This will crash React
        // state.root.parentNode.removeChild(state.root);
      }
    }
  };
});
```

**Comment by rikschennink** [comment]
Wrap the tick `<div>` in another `<div>`, see render method below:

```jsx
return (
      <div>
        <div ref={this._tickRef} className="tick">
          <div data-repeat="true" aria-hidden="true">
            <span data-view="flip">Tick</span>
          </div>
        </div>
      </div>
);
```

Now React controls the root `<div>` and Tick controls the root child `<div>`.

**Comment by rikschennink** [comment]
Closed because inactive.
