### ISSUE TITLE
no timer is rendered, using count.schedule with 'from 1:20 till 2:50 every 30 minutes'

### ISSUE THREAD

**Issue by adas172002** [pqina/flip#16]
Hi, 

I am trying to display a rather complex timer schedule that basically consists of several `from .. till .. every xx minutes`. It seems that no matter what I pass as argument to `count.schedule`, nothing is rendered. Instead, I get 
```html
<div class="tick" data-did-init="handleTickInit" data-state="initialised">

    <div data-repeat="true" data-layout="horizontal center fit" data-transform="preset(h, m, s) -> delay">

        
    </div>

</div>
```
in the DOM and Tick fails silently. 

My actual code in `handleTickInit` function look like this:
```js
Tick.count.schedule(
    'every day at 18:30, from 1:20 till 2:50 every 30 minutes, from 8:30 till 10:20 every 25 minutes, from 12:20 till 14:20 every 30 minutes, from 21 till 22:15 every 25 minutes', {format:['h', 'm', 's']}
    ).onupdate = function(value) {
  tick.value = value;
};
```
Removing all `from .. till .. every .. minutes` makes Tick work as expected.

BTW. Really looking forward to using `count.schedule` as it seems to be a perfect fit for my needs. Thanks for your time!

**Comment by rikschennink** [comment]
I'd advise to lower the complexity of the schedule step by step, until it works. That should give a better indication of the problem, difficult to tell by looking at the code.

```
every day at 18:30, 
from 1:20 till 2:50 every 30 minutes, 
from 8:30 till 10:20 every 25 minutes, 
from 12:20 till 14:20 every 30 minutes, 
from 21 till 22:15 every 25 minutes
```

**Comment by adas172002** [comment]
Hi Rik,

I have tried to troubleshoot my code by simplifying as you suggested. It seems that everything more complex than `at 12:00` is not working as expected. I ended changing each `from .. till .. every .. minutes` to `at ..`. This works.

**Comment by rikschennink** [comment]
I'll run a test next week

**Comment by rikschennink** [comment]
Looks like hourly scheduling like this was broken, fixing now

**Comment by rikschennink** [comment]
Should be fixed in version 1.7.6

**Comment by adas172002** [comment]
Great! I will have a look at ver 1.7.6 in two weeks, thanks for your help.

**Comment by adas172002** [comment]
1.7.7 works as expected.
