### ISSUE TITLE
Flip takes too long when using with a large number

### ISSUE THREAD

**Issue by sanjshah** [pqina/flip#20]
Hi,

I am using the flip with a large number 5399 but although I have set the 

`                                    <div data-layout="horizontal right" data-repeat="true" data-transform="arrive(9, .005) -> round -> pad('  ') -> split -> delay(rtl, 10, 50)">
                                        <span data-view="flip"></span>
                                    </div>`

I am looking to ensure the flip is completed within 5 seconds.

Any help is appreciated.

**Comment by rikschennink** [comment]
Please provide a public test case, happy to take a quick look.

**Comment by rikschennink** [comment]
Closed because after two months, no public test case was provided.
