### ISSUE TITLE
Usage with Pure JS: Create countdown

### ISSUE THREAD

**Issue by fgarcia5** [pqina/flip#22]
I am trying to implement this library in my Framework7 project (with pure Javascript) and I'm having some problems. I would like to know if you can help me.

I want to create, a kind of Pomodoro, like this (https://codepen.io/putraaryotama/pen/wgwqBB) but with @pqina/flip.

In this Sandbox you can see how far I have advanced: https://codesandbox.io/s/loving-feather-hmcx6

The points that I am not achieving are the following:
1. "autostart" to false: when I instantiate the count.down that does not start automatically
2. Colon ":" between minutes and seconds
3. Update the value of count.down and the view when doing "reset" with the value entered in the stepper (variable "tickTimeSelected") and when the stepper value change with Contdown stopped.

The whole implementation is in the file "src/pages/home.f7.html". 

I have read the complete documentation (https://pqina.nl/tick/) and tried many alternatives but I cannot unlock those points, I would appreciate if you can help me.

Thank you, Fabricio

**Comment by rikschennink** [comment]
I'm sorry, I can't help with that. I advise to check out the various examples on the product page and see which parts you need to combine. There's a stop watch on there as well.
https://pqina.nl/flip/preset-stopwatch.html

Will close because issues are for bugs only.

**Comment by fgarcia5** [comment]
> I'm sorry, I can't help with that. I advise to check out the various examples on the product page and see which parts you need to combine. There's a stop watch on there as well.
> https://pqina.nl/flip/preset-stopwatch.html
> 
> Will close because issues are for bugs only.

Thanks for your answer.

Asking you a single favor, in this example, could you tell me how to get the ":" to be displayed correctly, with "text" format?https://codesandbox.io/s/loving-feather-hmcx6?file=/src/pages/home.f7.html

I am not being able to figure out how to make it work. I have even tried with [Tick View Property](https://pqina.nl/tick/#tick-view-property) but not work


Thanks a lot.

**Comment by rikschennink** [comment]
If you can create a fast demo I'm happy to take a quick look but this codesandbox is quite slow.

**Comment by fgarcia5** [comment]
I updated the example with a minimal implementation. I need implement the flip countdown in a Framework7 project (Pure JS and Webpack) and there the library doesn't work like CDN example implementations.

https://codesandbox.io/s/loving-feather-hmcx6?file=/src/pages/home.f7.html
Or the repo with the same minimal project: https://github.com/fgarcia5/f7-core-test
 
Thanks a lot for your time @rikschennink

**Comment by rikschennink** [comment]
@fgarcia5 I'd advise to create a simple vanilla sandbox and import flip there. 

The current sandbox needs to install all kinds of npm packages.

I cannot edit this sandbox.

I think you need to set this `data-view` to text. You don't need a repeater.

`<span data-view="flip" data-key="sep" class="tick-text-inline"></span>`

Please see: https://pqina.nl/flip/preset-local-time.html

**Comment by fgarcia5** [comment]
I tried the alternatives you gave me and the behavior is the same.

Sorry for the mess, now I could create a minimal project without npm packages:
https://codesandbox.io/s/frosty-sinoussi-x632p?file=/pages/home.html

You could review it?

Again, thank you @rikschennink

**Comment by rikschennink** [comment]
https://codesandbox.io/s/xenodochial-dan-rpitg?file=/pages/home.html

**Comment by fgarcia5** [comment]
Thanks a lot @rikschennink 

Here a Flip Countdown example with Framework7 Stepper and Init/Stop functions. Maybe someone can help: https://codesandbox.io/s/frosty-sinoussi-x632p?file=/pages/home.html

Best regards, Fabricio.
