### ISSUE TITLE
AngularJS availability?

### ISSUE THREAD

**Issue by RipleWare** [pqina/flip#23]
Hi there,

Love the component and would love to use it in my application, but I am unsure how to port it over to Angular.
I don't suppose you have any knowledge how to make this available in an AngularJS application?

**Comment by rikschennink** [comment]
Hi, I'm no expert with Angular, I think you could take a look at the React implementation and duplicate lots of it to get it to work with Angular as well. (https://github.com/pqina/flip/issues/1)
