### ISSUE TITLE
Calculate font size on height

### ISSUE THREAD

**Issue by siedi** [pqina/flip#25]
Hi,

using this create plugin as a clock in my smart home dashboard

<img width="307" alt="Bildschirmfoto 2021-01-16 um 16 12 52" src="https://user-images.githubusercontent.com/4923159/104815604-de2d4b80-5815-11eb-8ab6-c4748727f409.png">

While the auto-resize horizontally (width) works quite fine, it doesn't in the height. Thus, it overlaps if there is not enough space (see image). 

Is there any chance to get that implemented as well?

Thanks
Siedi

**Comment by rikschennink** [comment]
Hi that's not possible currently. You could wrap the flip clock in another element that is scaled relatively to the remaining height, give it the aspect ratio of the flip clock and the width should be limited correctly. Will require some CSS but should work.
