### ISSUE TITLE
Is it against your terms of use to remove the credits?

### ISSUE THREAD

**Issue by MartinMbae** [pqina/flip#28]
If I removed the "Powered by PQINA" credits from my website, will that count as going against your term of use.

![image](https://user-images.githubusercontent.com/48010340/109751872-6910ac80-7bf0-11eb-86e3-d942411960c8.png)

**Comment by rikschennink** [comment]
No, you’re free to remove it, but to support development please consider linking to pqina.nl somewhere else.

**Comment by MartinMbae** [comment]
Thanks. I definitely will.
