### ISSUE TITLE
Error: Uncaught Can't get extension with name "elay"

### ISSUE THREAD

**Issue by chamikabm** [pqina/flip#3]
I'm always getting this error even with the example index.html, when it is hosted on a web server But in localhost it works as expected.

`Uncaught Can't get extension with name "elay", "elay" is not available. The following extensions are available: "ascii", "char", "tween", "value", "input", "rotate", "map", "transform", "upper", "lower", "abs", "add", "subtract", "modulus", "pad", "number", "replace", "round", "ceil", "floor", "fraction", "percentage", "multiply", "divide", "split", "format", "plural", "limit", "reverse", "arrive", "spring", "delay", "step", "keys", "duration", "substring", "preset"`

**Comment by rikschennink** [comment]
It looks like your transform chain contains a "elay" transform instead of a "delay" ?

Not sure what that happens, might be your build script.

**Comment by rikschennink** [comment]
closed because inactive for 10 days
