### ISSUE TITLE
Schedule "every 2 days" or "every 48 hours"

### ISSUE THREAD

**Issue by marcdomancie** [pqina/flip#32]
Hello there, 

I am wanting to achieve an evergreen countdown timer that repeats itself every 2 days or 48 hours with **tick.count.schedule()**

I have tried both: 
- Tick.count.schedule('**every 48 hours at 23:59:59**')
- Tick.count.schedule('**every 2 days at 23:59:59**')

But I don't think that the logical English syntax is supported.

How can I achieve this?

**Comment by rikschennink** [comment]
I don't think that's currently possible.

**Comment by marcdomancie** [comment]
I have a sample working thanks!

// Resets Monday, Wednesday, Friday, Sunday
// Except Monday is a 24 hour countdown and not 48 hour

Tick.count.schedule('every monday at 23:59:59, every wednesday at 23:59:59, every friday at 23:59:59, every sunday at 23:59:59',{ timezone: '+10:00' }).onupdate = function(value) { 
            tick.value = value;
  }
