### ISSUE TITLE
How to on integrating JQuery handleTickInit

### ISSUE THREAD

**Issue by nikolaosinlight** [pqina/flip#35]
Hi,

Flip is absolutely awesome.  It is super simple to setup a count down timer.

My challenge is that we are heavily utilizing JQuery and it isn't obvious how to have the "data-did-init" invoke a JQuery method to do a countdown OR how to wire up the method from JQuery (I would expect this is the approach needed).

Say I have the following HTML:
```
          <div id="preview-countdown" class="tick">
            <div data-repeat="true" data-layout="horizontal center fit" data-transform="preset(d, h, m, s) -> delay">
              <div class="tick-group">
                <div data-key="value" data-repeat="true" data-transform="pad(00) split -> delay">
                  <span data-view="flip"></span>
                </div>
                <span data-key="label" data-view="text" class="tick-label"></span>
              </div>
            </div>
          </div>
```
How would I be able to from JQuery attach my own "handleTickInit" method?

I suspect the solution involves using the find method and have tried the following but it complains that "Uncaught TypeError: Cannot read properties of undefined (reading 'count')"

```
      $('#preview-countdown').tick.count.down(new Date(previewMode), {
       format: ['d', 'h', 'm', 's'],
       interval: 1000
       }).onupdate = function(value) {
            $.tick.value = value;
       };
```

What is strange is that I see the tick is initialized by the fact that the data-state says so but just don't know how to attach the method to handle the tick object.  Ultimately, I assume it is super simple and others might benefit from docs updated to include this manner to access this great counter.

<div id="preview-countdown" class="tick" data-state="initialised">

Thanks!

**Comment by rikschennink** [comment]
It should be something like this

```js
$('#preview-countdown').tick('create', {
    didInit: function(tick) {
        // Tick.count.down() here
    }
});

```

**Comment by nikolaosinlight** [comment]
Thanks for the reply.  My problem is still there.  Perhaps a screen shot might help:

<img width="588" alt="Screen Shot 2021-10-06 at 2 54 31 AM" src="https://user-images.githubusercontent.com/10455508/136154677-94553913-a14a-496c-98ef-93d499174f56.png">

**Comment by nikolaosinlight** [comment]
Hmmm... No... I simply looked at the example folder which only references:
flip.min.js and flip.min.css

But looking at the dist folder I see there is:
tick.view.flip.jquery.min.js

But then there is a flip.module.js which references the ../tick folder

Quite simply if I wanted to only use flip with JQuery what JS files would I need to import?  Clearly the following is not sufficient:
  <script type="text/javascript" src="/assets/js/tick.view.flip.jquery.min.js"></script>

It also might be helpful to have a JQuery example in the examples folder.
Thanks!

**Comment by nikolaosinlight** [comment]
I should also point out I tried using the argument tick in the function block (i.e. changed $.tick to tick) but that fails.

Strange that the call with tick as an argument cannot be used to access the counter but it is what it is I guess.

I appreciate your insights and sharing a great plugin!

**Comment by nikolaosinlight** [comment]
Okay... so I tried plugging in a date string and now I get numerics for the value array HOWEVER still no flip counter visually.

<img width="448" alt="Screen Shot 2021-10-06 at 4 10 00 AM" src="https://user-images.githubusercontent.com/10455508/136164908-ec51431a-28bf-4886-92df-9efc1feedbe5.png">

Something is clearly still missing.  This is really painful... :-(

**Comment by rikschennink** [comment]
If you can make a reproduction on https://codesandbox.io I'm happy to take a quick look.

**Comment by rikschennink** [comment]
Closed because inactive

**Comment by nikolaosinlight** [comment]
Hello... apologies for not getting back to this sooner... I have finally found the time to circle back to this and I took your example in the flip-master project and create a version on https://codesandbox.io and shared it with you.

I would sincerely appreciate it if you could take a look.  The flip counter is simply not rendering.  If you could resolve the issue then might be worthwhile to include this example as a jquery variant in your project if you like.

Hoping you can help me out and this can help others in the future.  This flip counter is truly amazing!

**Comment by rikschennink** [comment]
This is the error I see when I check "preserve log"

> ReferenceError: Can't find variable: $

So apparently jQuery is not loading

**Comment by nikolaosinlight** [comment]
Hi @rikschennink,

Circling back b/c I really want to resolve this.  I am not an export on codesandbox.io and I am not even sure where it is even reporting that that JQuery cannot load.  Could I ask you to please simply help massage the example I provided into a working example that leverages JQuery.  I love the Flip component but it is the ONLY component not using JQuery in our Apps.

Thank You Kindly!

**Comment by mailandr** [comment]
@joseoconnor I had the same problem. Here's how I implemented it:

```html
<head>
    <script type="text/javascript" src="js/tick.core.jquery.js"></script>
    <script type="text/javascript" src="js/tick.view.flip.jquery.min.js"></script>

    <link rel="stylesheet" type="text/css" href="css/tick.view.flip.min.css">
    <link rel="stylesheet" type="text/css" href="css/tick.core.css">
</head>
```

```html
<div class="tick">
    <div data-repeat="true" data-layout="horizontal fit" data-transform="preset(d, h, m, s) -> delay">
        <div class="tick-group">
            <div data-key="value" data-repeat="true" data-transform="pad(00) -> split -> delay">
                <span data-view="flip"></span>
            </div>

            <span data-key="label" data-view="text" class="tick-label"></span>
        </div>
    </div>
</div>
```

```javascript
$('.tick').tick('create', {
    didInit: function (tick) {
        $.tick.count.down('2025').onupdate = function(value) {
            tick.value = value;
        };
    },
});
```
