### ISSUE TITLE
Customising style for tick-flip-panel in React

### ISSUE THREAD

**Issue by pseudonator** [pqina/flip#36]
Whats the best way to style `tick-flip-panel` in React.js ?
I saw that its possible to pass in a view to `Tick.DOM.create` but couldnt find any examples of it.
Im specifically looking at ways to dynamically change the color of `tick-flip-panel`

**Comment by rikschennink** [comment]
With CSS?

I'm not sure what you mean, you can set styles to individual elements within the ticker using style selectors.
