### ISSUE TITLE
How to use flip in a React function component to show a timer ?

### ISSUE THREAD

**Issue by Raghav-Kumar-Jha** [pqina/flip#4]
Hi, A great Thanks for your amazing contribution to make the flip package available as an npm module. 
I have tried to import it to display a simple flip timer (that should display time form 00:00 sec until an event (function) get fired. I want to stop the watch when the function is called. 
****
**Can you please show an example to show the timer in a React functional component using hooks?**

**Comment by rikschennink** [comment]
https://github.com/pqina/flip/issues/1
