### ISSUE TITLE
import Tick :  Cannot use import statement outside a module

### ISSUE THREAD

**Issue by galiolas** [pqina/flip#41]
Hey I have a problem when installing the package in my projet.

...\node_modules\@pqina\flip\dist\flip.module.js:1
import Tick from '@pqina/flip/tick/tick.core.module';
^^^^^^
SyntaxError: Cannot use import statement outside a module

I can't put 'type:'module' ,in my package.json or i have another error.

I'm using ES6

My dependecies :
"@babel/core": "^7.12.3",
"react": "16.13.1",

**Comment by rikschennink** [comment]
Please use search before posting

https://github.com/pqina/flip/issues/37
