### ISSUE TITLE
Unable to build a count down timer in React. 

### ISSUE THREAD

**Issue by Raghav-Kumar-Jha** [pqina/flip#5]
How can I use this npm module to make a count down timer in a react function component?
I am working on an online test project, and want to display the rest time left of the exam with the help of the flip clock. How to use this? 

![Timer](https://user-images.githubusercontent.com/36503061/79116219-843eb780-7da5-11ea-9025-45568e2a3be1.JPG)

**Comment by rikschennink** [comment]
https://github.com/pqina/flip/issues/4
https://github.com/pqina/flip/issues/1
