### ISSUE TITLE
@pqina/flip for Nuxtjs not working

### ISSUE THREAD

**Issue by wahibAbdou** [pqina/flip#52]
Hey guys, I tried to use @pqina/flip library but just won't work I copied the component code in here [codesandbox vue flip](https://codesandbox.io/s/vue-flip-demo-xhtfk?file=/src/components/Flip.vue) but I get this error
<img width="1677" alt="Screen Shot 2022-10-26 at 11 44 06" src="https://user-images.githubusercontent.com/59398231/198006572-63f9db6b-b2ad-4c06-bca8-73744132c27f.png">
package.json
<img width="1680" alt="Screen Shot 2022-10-26 at 11 45 51" src="https://user-images.githubusercontent.com/59398231/198006902-9827466f-026a-4cb0-bb1a-c6ad77712508.png">
my component
<img width="1680" alt="Screen Shot 2022-10-26 at 11 46 54" src="https://user-images.githubusercontent.com/59398231/198007102-d33c1c0b-265b-4f31-baef-ccde4a95f171.png">

**Comment by rikschennink** [comment]
Just opened the page, it seems to work just fine?

<img width="359" alt="Screenshot 2022-11-07 at 09 01 44" src="https://user-images.githubusercontent.com/1132575/200256821-7dfa4e43-97c7-4df0-9c5a-e5ee51c1ce19.png">
