### ISSUE TITLE
Shein documentary...

### ISSUE THREAD

**Issue by june07** [pqina/flip#60]
So, I'm watching [this documentary on Shein](https://www.imdb.com/title/tt22816826/) right now and just happen to recently/currently have used your project in [a project of my own](https://github.com/synchook), thus the imagery from 13:05 into the film brought me here to post this...

![image](https://user-images.githubusercontent.com/11353590/224563431-c97370f8-af2c-4df0-aee2-6cc4777340ea.png)

I realize I may be really naive right now because I have no idea what other products out there provide a similar web UI as flip (obviously it could be done in plain CSS and just similar code) ... nor have I got to the [Shein web site](https://us.shein.com/) to investigate if they are in fact using your library, BUT... I thought it certainly interesting enough to bring to your attention.

Thanks for the great library, love your work, and if you don't know... know you know. Cheers.

**Comment by rikschennink** [comment]
Appreciate it ❤️

I couldn't the big one, but I found a small countdown flipper on the site. I think this is another plugin as the HTML looks different and it doesn't have the "physics" like bounce at the end :)
