### ISSUE TITLE
How to set flip panel mode?

### ISSUE THREAD

**Issue by joshuasosa** [pqina/flip#62]
Hello, I got flip working well but want to change it from bounce to something else. Instead of the flip panel coming down and bouncing when it hits, I'd like it to just stop and not bounce. How do I do that? The Flip page says there are flip panel modes, but doesn't give examples of what those look like or how to use them.

**Comment by rikschennink** [comment]
Hi, you can use `flip-easing` https://pqina.nl/tick/#flip in the `data-style` property.

**Comment by joshuasosa** [comment]
It worked, thanks! I think it'd be useful to include notes and examples down where I expected to find such info: in the Easing tab of Transitions (https://pqina.nl/tick/#transitions-easing). That easing tab could be more useful than just listing easings.

**Comment by rikschennink** [comment]
Glad to hear that @joshuasosa, and thanks for the suggestions!
