### ISSUE TITLE
If you load the website in a separate tab, the animation does not run

### ISSUE THREAD

**Issue by jaime070791** [pqina/flip#66]
Hello, I have a problem:
If you load the website in a separate tab, the animation doesn't even start
what could be done?

**Comment by rikschennink** [comment]
I've reproduced the issue, will look into it as soon as possible.

**Comment by rikschennink** [comment]
Should be fixed in 1.8.2

**Comment by jaime070791** [comment]
Now it runs well
Thank you!!!

**Comment by rikschennink** [comment]
Glad to hear that :)
