### ISSUE TITLE
Methods for pause, resume and reset countdown

### ISSUE THREAD

**Issue by ezimmert** [pqina/flip#7]
Hi,
Is there any possibility to pause, resume and reset a countdown from Tick.count.down method?
Thanks!

**Comment by rikschennink** [comment]
Pausing a count down doesn't work as when you resume the count down the amount of time to the target date will have changed.

You can pause the updates of the counter itself, see: https://pqina.nl/flip/preset-stopwatch.html

**Comment by ezimmert** [comment]
Perfect, thanks!
