### ISSUE TITLE
Example with NPM

### ISSUE THREAD

**Issue by diego-betto** [pqina/flip#73]
Hi, 

Can I ask you if you can complete this minimal example? 

https://codesandbox.io/p/sandbox/4rrdxd

It seems that when using npm/import functions defined within `data-did-init` are never called. 

From the DOCS it seems that it's enough to import the module
`import tick from @pqina/flip';`

But I cannot get it to work.
Any hint? 

Thanks a lot

**Comment by rikschennink** [comment]
I've created an example here: https://stackblitz.com/edit/flip-counter-module

**Comment by diego-betto** [comment]
Ah ok! 

Thank you!
